### ISSUE TITLE
mavanimes.co

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#201]
**Website**

* `http://www.mavanimes.co/fairy-tail-245-vostfr/`

**Problem**

* ads

**Ss**

* https://i.vgy.me/s7ndZN.png

**Fix**

```
mavanimes.co#$#abort-on-property-read _0xb36c
```

**Comment by mapx-** [comment]
@wizmak 
see https://forums.lanik.us/viewtopic.php?f=64&t=44955

switching episodes feature is broken, any other filter `#$#abort-on-property-read open` will break the same feature, so you should ask the devs to dig in on why this happens (all fine in uBO)

just begin with removing that wrong filter: `mavanimes.co#$#abort-on-property-read _0xb36c`

The popups are still there with / without that filter (originating from `mavplay`)

**Comment by wizmak** [comment]
> switching episodes feature is broken, any other filter `#$#abort-on-property-read open` will break the same feature, so you should ask the devs to dig in on why this happens (all fine in uBO)

Strange, that feature works well on my end.

> just begin with removing that wrong filter: `mavanimes.co#$#abort-on-property-read _0xb36c`
> 
> The popups are still there with / without that filter (originating from `mavplay`)

This filter is useless now anyways, will remove it.

@mapx- Thanks!

**Comment by lemav07** [comment]
@wizmak hi brother please actually using adblock or adblock plus we cant switch episodes because there is a filter that blocks it here is an url where you can make a try : http://www.mavanimes.co/no-guns-life-15-vostfr/

Up the video « liste de tous les épisodes » you cant switch using abp or ab so please help us sir it would be really appreciated and sorry for disturbing you ..

**Comment by wizmak** [comment]
> @wizmak hi brother please actually using adblock or adblock plus we cant switch episodes because there is a filter that blocks it here is an url where you can make a try : http://www.mavanimes.co/no-guns-life-15-vostfr/
> 
> Up the video « liste de tous les épisodes » you cant switch using abp or ab so please help us sir it would be really appreciated and sorry for disturbing you ..

@lemav07 Hey!
(cc @mapx- ) 
I see the issue now, `abort-on-property-read open` indeed breaks that episode switch function, will remove the filter.

This issue might be due to snippets being executed multiple times on pages with embedded iframes, not sure though so will need to confirm with the devs.

**Comment by lemav07** [comment]
@wizmak i updated the list but the problem is still here so i have analyzed a few to provide you more information and i saw where is the problem comming from look :
here : http://www.mavanimes.co/naruto-11-vf/

we are using a embed code of a player which domain is : embed.mystream.to and the switch is not working
the problem occurs only when there is this embed player in the post or pages so it seems that you blocked ads or something recently for this domain and its impacting the website can you try to see the link i sent you there is a filter that blocks the switch because of this domain mystream.to

and this is using ab and abp please help bro !!

users are all crying and because they use abp and ab i really need your help my friend im waiting your answer thanks

**Comment by wizmak** [comment]
@lemav07 
I removed the filter just a minute ago, give it a few minutes, then update your filter lists, issue should be resolved then.

**Comment by lemav07** [comment]
@wizmak i have waited 30 mins updated all tryied with adblock and adblock plus but the problem is still here you can try from your end it doesnt switch episodes look : http://www.mavanimes.co/naruto-11-vf/

**Comment by lemav07** [comment]
try to switch episode and then again and again its not working :s

**Comment by mapx-** [comment]
@wizmak I guess is due to this filter
`mstream.website#$#abort-on-property-read open`

how can be whitelisted a filter li8ke this ?
I tried 
```
mstream.website#@$#abort-on-property-read open
mstream.website#$@#abort-on-property-read open
```

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/88413377-5ffa6a00-cddb-11ea-8248-f52b737cdc3f.png)

**Comment by mapx-** [comment]
All the `open` filters are breaking the page even used in frames, definitely a snippet issue

**Comment by wizmak** [comment]
> I guess is due to this filter
> `mstream.website#$#abort-on-property-read open`
> 

True, I missed it cause I added it after I removed `mystream.to`

> how can be whitelisted a filter li8ke this ?
> I tried
> 
> ```
> mstream.website#@$#abort-on-property-read open
> mstream.website#$@#abort-on-property-read open
> ```

Unfortunately, snippet filters can not be whitelisted, so the above won't work, is this possible in uBO?

**Comment by mapx-** [comment]
yes, we use the same syntax as for hiding filters

**Comment by mapx-** [comment]
You could ask devs to remove that completely useless `$` from `#$#`

**Comment by wizmak** [comment]
> @wizmak i have waited 30 mins updated all tryied with adblock and adblock plus but the problem is still here you can try from your end it doesnt switch episodes look : http://www.mavanimes.co/naruto-11-vf/

@lemav07 Just removed the other domain from the problematic filter, try again in a few minutes.

**Comment by wizmak** [comment]
> This issue might be due to snippets being executed multiple times on pages with embedded iframes, not sure though so will need to confirm with the devs.

I confirm this is an issue with the behaviour of `abort-on-property-*` snippets, which should be fixed as of ABP 3.10, will re-add once it's a live.

**Comment by lemav07** [comment]
i really appreciate all the help you did today with me and everything you did i really thank you all guyz i hope the issue is solved now and people can switch episodes thanks for everything wish you all the best !

**Comment by lemav07** [comment]
please last question in how many time it will update automaticaly adsblocks for users ?

**Comment by wizmak** [comment]
> please last question in how many time it will update automaticaly adsblocks for users ?

 The anti-cv list is updated every one hour.

**Comment by wizmak** [comment]
Closing this as it does not seem to be an issue any more.

**Comment by mapx-** [comment]
@wizmak 

see breakage => https://forums.lanik.us/viewtopic.php?p=164559-mavanimes-co#p164559

I guess it's due to using this wrong approach (for a lot of sites)

`abort-on-property-write JSON.parse`

**Comment by wizmak** [comment]
> 
> see breakage => https://forums.lanik.us/viewtopic.php?p=164559-mavanimes-co#p164559
> 
> I guess it's due to using this wrong approach (for a lot of sites)
> 
> `abort-on-property-write JSON.parse`

@mapx- Thanks for pinging me. 
I replaced the problematic filter for that particular domain. As for other websites that might have some broken functions because of the same filter, we can fix issues as they arise, but I'd leave it to @smed79 & @manuel-martinez-dev to decide.
