### ISSUE TITLE
elektroda.pl (2)

### ISSUE THREAD

**Issue by kulfoon** [abp-filters/abp-filters-anti-cv#383]
Did you miss [my comment](https://github.com/abp-filters/abp-filters-anti-cv/issues/372#issuecomment-624164660) or what?

**Comment by wizmak** [comment]
@kulfoon You could have pinged me in the original issue, but anyways, this should be fixed, for now.

> Did you miss [my comment](https://github.com/abp-filters/abp-filters-anti-cv/issues/372#issuecomment-624164660) or what?

Well, No & yes. Your suggestion didn't really help, and I wanted to take a look to come up with a solution, had no time back then, then it slipped my mind, good?

Now, I'm not sure if this is the best way to contribute (assuming this is what you want to achieve here), and your expressing is somehow aggravating, please keep this in mind.

**Comment by kulfoon** [comment]
> wizmak : @kulfoon You could have pinged me in the original issue

I did ping both of you, after 4 days, in the same comment, by editing it.

> wizmak : Well, No & yes. Your suggestion didn't really help, and I wanted to take a look to come up with a solution, had no time back then, then it slipped my mind, good?

No problem, I do appreciate, that's why I asked, in case you forgot or missed my comment, to save my time, I wrote a comment and waited 4 days, nothing, then pinged you and waited another day, still nothing, so I just asked what's going on with the issue, good? Just a question, I didn't mean to offend you in anyway, why then taking it so personally...seems you're overreacting. Also you could have leave a comment saying you're working on solution, otherwise how do I know/determine whether you have seen my comment and are working on a solution, or just have missed/forgot my comment.

>  wizmak  : Now, I'm not sure if this is the best way to contribute (assuming this is what you want to achieve here), and your expressing is somehow aggravating, please keep this in mind.

As explained above, I just asked, then you harassing me personally, for nothing, now, I'm not sure if this is the best way to contribute (assuming this is what you want to achieve here), and your expressing is somehow aggravating, please keep this in mind. See yourself got beaten by your own argumentation. Why even making a drama just because someone asked a question... So far, you haven't proven anything wrong with me in my commentary, you only throw general slander because you have imagined something. Can we stop it now? Coz if you're gonna continue your imagination, then I'll have to report you to the github administration for baseless harassment.
