### ISSUE TITLE
abp-filters-anti-cv blocking some eBay search results

### ISSUE THREAD

**Issue by eburtonlab** [abp-filters/abp-filters-anti-cv#946]
### List the website(s) where you encounter issues with ABP filters 

``ebay.com``

### Define the problem 

The anti-circumvention filters appear to be inappropriately blocking some non-sponsored eBay search results. 

The number displayed at the top of the eBay results does not correspond to the number of listings displayed while the filters are active. Disabling the anti-circumvention filters and reloading the page restores the missing results. The results are organic, non-sponsored listings and should not be blocked.

It is not clear why the affected results are being blocked, but the numbers of results affected are considerable -- on the order of 20% of the returned results in some larger searches.

### List all of your filter lists 

FIlterlist: ABP filter

### Tell us about your system configuration 

Windows 10 21H1
Firefox Developer 100.0b6 (64-bit)
Ad Block Plus 3.11.4

### Other details 

Some examples and discussion of this problem can be found here:

https://community.ebay.com/t5/Share-eBay-Technical-Issues/eBay-search-results-are-bugged-on-desktop/m-p/32872149/highlight/true#M98472

An example search that should currently return one visible result that is blocked if the ABP filter is active:

https://www.ebay.com/sch/i.html?_from=R40&_nkw=125229606546&_sacat=0&_dmd=1&rt=nc

**Comment by ebayissues** [comment]
https://community.ebay.com/t5/Share-eBay-Technical-Issues/There-is-something-massively-wrong-with-search/m-p/32880823#M98735

This issue is effecting a lot of sellers. Including Top Rated and Retail Stores that sell on eBay. AdBlock ABP filter is blocking listings from Best Buy and Sony for a couple of examples.

**Comment by samuraifez** [comment]
This is a massive issue and definitely should be dealt with ASAP; it is negatively affecting an untold numbers of independent sellers and their income streams.

**Comment by manuel-martinez-dev** [comment]
Thanks for the report.

I've made some adjustments, which should resolve the issue you're facing. it can take up to an hour give or take for you to see it reflected on your end, but try to update your lists on the extension.

**Comment by eburtonlab** [comment]
I appreciate the quick response! My preliminary tests with the updated filters indicate agreement between the number shown at the top of the eBay search results and the actual results displayed, so it appears the adjustments worked. Thanks again!

**Comment by Sigimi8** [comment]
Hello, this is an issue for many of us as sellers. This is still an issue,

> Thanks for the report.
> 
> I've made some adjustments, which should resolve the issue you're facing. it can take up to an hour give or take for you to see it reflected on your end, but try to update your lists on the extension.

Hello, this is an issue for many of us as sellers. This is still an issue unfortunately, ABP (and AB) are still blocking promoted listings on eBay. Our sales have gone down drastically.

**Comment by ebayissues** [comment]
Yes, all Promoted Listings are being blocked. It Best Match on ebay search is turned on (it is by default). It will fully block sellers listings.

**Comment by manuel-martinez-dev** [comment]
Hello,

Please note that blocking posts that are labelled as _**"Sponsored"**_ is the **intended behavior** of the list, as this type of posts are considered circumvention ads.

In case you notice that listings that are **not** tagged as _**"Sponsored"**_ are being hidden, please provide us with a screenshot with clear examples.

Thanks,

PS: if it helps, within the extension there's an option that when enabled, it can help verifying what's being hidden, you can go to the advanced settings and tick the "debugging" option (see screenshot).

![debugging-ext](https://user-images.githubusercontent.com/40897997/165624006-2c4f8313-029d-40e1-b3c0-985cd8f4ab9b.png)

**Comment by Sigimi8** [comment]
> circumvention

Hello,

This was a change that recently affected eBay the last week it seems, if this is an option, it should not be on by default since it's impossible to classify these as 'intrusive' or 'circumvention', it's simply the same listing you're looking for, but a seller chose to pay extra when an item sells for a higher placement, it still alligns with what the buyer wants, and should be considered a part of "show acceptable ads". If anything, it should be an option not on by default to hide sponsored ads, since the viewer is a buyer looking for such listings on eBay to purchase items, but can be locked out of ever knowing they exist, simply because they are unaware of an issue with Adblock/P which a large majority have installed.

Again, this is just for searching for items on a website that *is* full of 'ads' and or 'listings' so the statement and belief of it being circumvention or intrusive does not hold weight and is contradictory. This is completely different from the side ads/banners eBay shows, since you're not searching for those products.

**Comment by mtrin** [comment]
Ebay user here. To me it's sure intrusive and a circumvention. Regardless of what eBay believes it's right, this is up to the users to decide. As far as I know, adblockers still offer to disable Google search Ads by default and what's more important: Google won't make the process so difficult and also won't spam you with low quality ad results on every second listing and half. It's up to eBay to stop playing with adblockers and actually team up with them for a better user experience.

**Comment by pavelmalik** [comment]
Spammy Sponsored listings are now showing up again, even with the adblock plus enabled.

**Comment by nyanpasu64** [comment]
As an interim fix, I'm using a Stylus stylesheet to clearly (and maybe *too* ugly) mark sponsored results:

```css
    .s-item__detail--primary:last-child * {
        font-weight: 900 !important;
        color: red !important;
        font-size: 220px;
        line-height: 1.15;
    }
    .s-item__detail--primary:last-child > * > * {
        bottom: 1em !important;
        left: 0px !important;
    }.s-item__detail--primary:last-child > * > * > * > *:before {
        content: "████";
    }
```

![Screenshot_20221108_022427](https://user-images.githubusercontent.com/913957/200542551-64597aa3-9f5f-49ec-bf34-1a3abe03245c.png)

**Comment by pavelmalik** [comment]
> As an interim fix, I'm using a Stylus stylesheet to clearly (and maybe _too_ ugly) mark sponsored results:
@nyanpasu64 
Absolutely amazing, thanks for that!
